### ISSUE TITLE
[Bug]: GET /api/v1/models/:modelId 

### ISSUE THREAD

**Issue by sunnyark** [civitai/civitai#1100]
### What happened?

Recently, the [GET /api/v1/models/:modelId] API only returns information for the latest version of a model. 

### Steps to reproduce the problem

example https://civitai.com/api/v1/models/1102

### What should have happened?

What is the method to obtain information on all versions of a particular model?

**Comment by BlafKing** [comment]
Having the same issue.

**Comment by RedFoxNightfox** [comment]
can confirm with using API through a1111 webui with sd-civitai-browser-plus extension that only latest model gets reported.

**Comment by zixaphir** [comment]
I think this has been an issue since about 7PM GMT yesterday. I was actively writing changes for the new NSFW categories when it occurred, so I had assumed something in my code had broken. I was testing on a model with several versions and all the versions had been showing up, but after making some changes to my code, I made a fresh API call and it only returned the most recent model version. I hope this helps find what deployed code caused this issue.

**Comment by RikudouSage** [comment]
Well, now the endpoint returns 404.

**Comment by AA-Developer** [comment]
The problem also appears when filtering the result by user name

[https://civitai.com/api/v1/models?limit=10&sort=Newest&username=True_Might&page=1](url)

The API system has effectively stopped doing what it should
Some models information, such as the update date, also disappeared
I was also surprised that the meta image data disappeared and now had to be retrieved from the images API

**Comment by ChiaYen-Kan** [comment]
i also same problem, when use model api is can't get all model version information, only last version can be get
i use the urllib of python to get information is also same problem

**Comment by trdahl** [comment]
Instead of writing it happends to me to, let us just hope that the developer find a solution to our problem, because i bet its as much frustrating for you as for me ... now we just have to wait

**Comment by Synchronos** [comment]
Specifically whatever is assembling the JSON in the civit.ai API is incorrectly repeating the first modelVersion instead of the correct values.

`curl https://civitai.com/api/v1/models/36281 -H "Content-Type: application/json" -X GET`

If you examine the JSON all 4 items in the modelVersions array are identical.

**Comment by Heather95** [comment]
The issue seems fixed now.

**Comment by manuelurenah** [comment]
Thank you everyone for raising this issue, we have already pushed new changes that fixed this issue. I'll be closing this, but feel free to open it again if you ever find any problems with this endpoint

**Comment by RikudouSage** [comment]
@manuelurenah This issue is still not fixed, for example https://civitai.com/api/v1/models/92008 vs https://civitai.com/models/92008

**Comment by manuelurenah** [comment]
Good catch @RikudouSage this is a different issue, related but not the same. We'll look into this, thanks!

**Comment by RikudouSage** [comment]
@manuelurenah Great! Can you reopen the issue, or shall I create a new one?

**Comment by manuelurenah** [comment]
@RikudouSage It has been fixed already
