### ISSUE TITLE
[Bug]: API "GET /api/v1/images" returned HTTPCode 500 when fetch images

### ISSUE THREAD

**Issue by i11cn** [civitai/civitai#1199]
### What happened?

It failed when I get images by API : GET /api/v1/images

### Steps to reproduce the problem

1. Open browser and goto URL https://civitai.com/api/v1/images?limit=200&modelId=133005
2. Expect: Get json data from server contained the images infomation.
3. Actually: Got 500 error and the error message in body is:
{
  "error": "canceling statement due to statement timeout",
  "code": "57014"
}

### What should have happened?

Get json data from server contained the images infomation.

**Comment by AA-Developer** [comment]
Yes, it is not possible to get images and data like before from API.

https://civitai.com/api/v1/images?limit=100&sort=Newest&modelId=257749&modelVersionId=290640&browsingLevel=0&cursor=0

An empty response is obtained.
The problem occurred 8 hours ago.

**Comment by AldebaraanMKII** [comment]
Yeah i can`t get the API to download more than the first page using this powershell script:

`

Function Get-CivitAiImages {

    Param(
        [Parameter(Mandatory = $true, Position = 0)][string[]]$URLs
    )
    $API_Key = "YOURAPIKEYHERE"
    $BaseFolder = "DESTINATIONFOLDER"
    $Limit = 100

    foreach ($URL in $URLs) {
        # Extract the username from the URL
        if ($URL -match "https://civitai.com/user/([^/]+)/images") {
            $Username = $matches[1]
        } else {
            Write-Host "Invalid URL format: $URL"
            continue
        }

        $OutFolder = "$BaseFolder\$Username"
        $JSONPath = "$OutFolder\$Username.json"
        If (!(Test-Path $OutFolder)) {
            New-Item -Path $OutFolder -ItemType Directory | Out-Null
        }
        Set-Location $OutFolder

        $ImageJSON = @()
        $Page = 1

        do {
            $APIURL = "https://civitai.com/api/v1/images?username=$Username&token=$API_Key&limit=$Limit&page=$Page"
            try {
                $response = Invoke-WebRequest -Uri $APIURL -Headers @{"Content-Type" = "application/json"} -Method Get -UseBasicParsing
                $JSON = $response.Content | ConvertFrom-Json
                if ($JSON -eq $null -or $JSON.items -eq $null) {
                    Write-Host "Invalid JSON response for $Username on page $Page."
                    break
                }
                if ($JSON.items.Count -eq 0) { break }
                $ImageJSON += $JSON.items
                $Page++
            } catch {
                Write-Host "Failed to fetch or parse JSON for $Username on page $Page. Error: $_"
                break
            }
        } while ($JSON.items.Count -eq $Limit)

        if ($ImageJSON.Count -eq 0) {
            Write-Host "No images found for $Username."
            continue
        }

        $Global:i = 0
        $ItemCount = $ImageJSON.Count
        $Activity = "Downloading images for $Username... "

        $ImageJSON | ConvertTo-Json -Depth 10 | Out-File -LiteralPath $JSONPath -Force
        for ($i = 0; $i -lt $ItemCount; $i++) {
            $ImageURL = $ImageJSON[$i].url
            $FileName = [System.IO.Path]::GetFileName($ImageURL)
            try {
                Invoke-WebRequest -Uri $ImageURL -OutFile $FileName -UseBasicParsing
            } catch {
                Write-Host "Failed to download image $ImageURL for $Username. Error: $_"
                continue
            }

            $Global:i++; $Percent = 100 / $ItemCount * $Global:i
            $Status = " {0:n1}%:   {1} of {2}" -f $Percent, $Global:i, $ItemCount
            Write-Progress -Activity $Activity -Status $Status -PercentComplete $Percent
        }

        Write-Progress -Activity $Activity -Completed
    }
}

# List of URLs
$URLs = @(
    "https://civitai.com/user/USERNAME1/images",
    "https://civitai.com/user/USERNAME2/images",
    "https://civitai.com/user/USERNAME3/images"
)

# Call the function with the list of URLs
Get-CivitAiImages -URLs $URLs

pause

`

**Comment by tk101-fs** [comment]
I came to enter a similar issue but this one is close enough. I'll add that I think the 'Code 500' response seems specific to highly active / popular model versions, as the /v1/images endpoint responses from less popular models are far more stable with successful responses.

Specifically, the response for some models (seemingly popular / highly active ones as mentioned above) is:

```
{
    "error": "canceling statement due to statement timeout",
    "code": "57014"
}
```

### My uninformed thesis/guess:

**The failure rate for queries on some models is quite high (80-90%) depending on the time of day, and I'm thinking it probably has to do with the fact that, particularly when applying to "Most Reactions" sort to the API query, the images are getting reactions often enough that the state of the database is changing second by second, and this may be breaking the way the cursors and paging works.**

Even when no cursor is passed on the "Most Reactions" sort, probability of failure (error 500) can still be quite high, so it's not necessarily specific to using the cursor. I think it just is a server load / responsiveness shortfall because the sorting algorithm on Most Reactions can't keep up with the number of reactions being made to the model's images. Again, this is just my theory.

**Comment by manuelurenah** [comment]
Hey all, thank you for your patience with this issue. We have made an update and should be coming out shortly today. You can see the changes here https://github.com/civitai/civitai/commit/1c83cd037bfeb1fcc666fadb1d96c51558dd7034 which should fix this problem once and for all. 

If this is still an issue, please feel free to re-open this. Hope this helps!

**Comment by Martyprod** [comment]
> Hey all, thank you for your patience with this issue. We have made an update and should be coming out shortly today. You can see the changes here [1c83cd0](https://github.com/civitai/civitai/commit/1c83cd037bfeb1fcc666fadb1d96c51558dd7034) which should fix this problem once and for all.
> 
> If this is still an issue, please feel free to re-open this. Hope this helps!

issue is back for me since few days, with the api in comfyui on Wan 2.2 i2v :( (don't know about the other nodes yet or other models).
